// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type RequestLog struct {
	ID        int64
	CreatedAt time.Time
	UserAgent sql.NullString
	Ja3       sql.NullString
	H2        sql.NullString
	PeetPrint sql.NullString
	IpAddress sql.NullString
}
