// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: request_log.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const insertRequestLog = `-- name: InsertRequestLog :exec
INSERT INTO request_log (
    created_at,
    user_agent,
    ja3,
    h2,
    peet_print,
    ip_address
) VALUES (
    ?,?,?,?,?,?
)
`

type InsertRequestLogParams struct {
	CreatedAt time.Time
	UserAgent sql.NullString
	Ja3       sql.NullString
	H2        sql.NullString
	PeetPrint sql.NullString
	IpAddress sql.NullString
}

func (q *Queries) InsertRequestLog(ctx context.Context, arg InsertRequestLogParams) error {
	_, err := q.db.ExecContext(ctx, insertRequestLog,
		arg.CreatedAt,
		arg.UserAgent,
		arg.Ja3,
		arg.H2,
		arg.PeetPrint,
		arg.IpAddress,
	)
	return err
}
